import type { Playlist } from "./types";

/**
 * ⚠️  COPYRIGHT — READ BEFORE FILLING IN videoId
 * ------------------------------------------------------------------
 * Every track below is a commercially released Bollywood film song.
 * I have not searched YouTube for these and have not filled in any
 * videoId — per your instructions I only use videos you've confirmed
 * you have the right to use, or the rights holder's own upload with
 * embedding enabled.
 *
 * Before you ship, for each track:
 *   1. Find the official upload (the film's label — e.g. T-Series,
 *      Saregama, Zee Music, Sony Music India — not a fan re-upload).
 *   2. Confirm embedding is allowed (try it in an <iframe> locally;
 *      if YouTube blocks it, `onError` will just skip the track).
 *   3. Paste the 11-character video ID into `videoId` below.
 *   4. Double check `film` / `year` — I've left them blank rather
 *      than guess, since I can't verify them without searching.
 *
 * Adding a new song later is a one-line addition to the relevant
 * array below.
 */

const playlistOne: Playlist = {
  id: "nostalgia-radio",
  name: "Nostalgia Radio",
  tracks: [
    {
      id: "t-01",
      title: "Gulabi Aankhen",
      artist: "Mohammed Rafi",
      film: "The Train",
      year: 1970,
      duration: 300,
      videoId: "JkdHB8S15Co",
    },
    {
      id: "t-02",
      title: "Labon Ko",
      artist: "KK",
      film: "Bhool Bhulaiyaa",
      year: 0,
      duration: 300,
      videoId: "lUCUT6Ydeoo",
    },
    {
      id: "t-03",
      title: "O Mere Dil Ke Chain",
      artist: "Kishore Kumar",
      film: "Mere Jeevan Saathi",
      year: 0,
      duration: 300,
      videoId: "_w14bUcxl1c",
    },
    {
      id: "t-04",
      title: "Sach Keh Raha Hai Deewana",
      artist: "KK",
      film: "Rehnaa Hai Terre Dil Mein",
      year: 0,
      duration: 300,
      videoId: "hUVjx_RhMl0",
    },
    {
      id: "t-05",
      title: "Pal Pal Dil Ke Paas",
      artist: "Kishore Kumar",
      film: "Blackmail",
      year: 0,
      duration: 300,
      videoId: "f5dw3nafOuo",
    },
    {
      id: "t-06",
      title: "Barsaat Ke Mausam Mein",
      artist: "Kumar Sanu & Roop Kumar Rathod",
      film: "Naajayaz",
      year: 0,
      duration: 300,
      videoId: "Q_cq8__k--M",
    },
    {
      id: "t-07",
      title: "Yeh Shaam Mastani",
      artist: "Kishore Kumar",
      film: "Kati Patang",
      year: 0,
      duration: 300,
      videoId: "5ZaKMzJrzXQ",
    },
    {
      id: "t-08",
      title: "Tadap Tadap",
      artist: "KK",
      film: "Hum Dil De Chuke Sanam",
      year: 0,
      duration: 300,
      videoId: "qsiHgJbwJUE",
    },
    {
      id: "t-09",
      title: "Neele Neele Ambar Par",
      artist: "Kishore Kumar",
      film: "Kalaakaar",
      year: 0,
      duration: 300,
      videoId: "ThHYiiZTB1Y",
    },
    {
      id: "t-10",
      title: "Beete Lamhein",
      artist: "KK",
      film: "The Train",
      year: 0,
      duration: 300,
      videoId: "dkTok8ikw_4",
    },
    {
      id: "t-11",
      title: "Humein Tumse Pyaar Kitna",
      artist: "Kishore Kumar",
      film: "KHUDRAT(1981)",
      year: 0,
      duration: 300,
      videoId: "iTkTrVXwCsA",
    },
    {
      id: "t-12",
      title: "Aankhon Mein Teri",
      artist: "KK",
      film: "Om Shanti Om",
      year: 0,
      duration: 300,
      videoId: "tqmqB-4Xt9U",
    },
    {
      id: "t-13",
      title: "Musafir Hoon Yaaron",
      artist: "Kishore Kumar",
      film: "Parichay",
      year: 0,
      duration: 300,
      videoId: "DuqZWlNEfnQ",
    },
    {
      id: "t-14",
      title: "Dil Ibaadat",
      artist: "KK",
      film: "Tum Mile",
      year: 0,
      duration: 300,
      videoId: "fKIJhHUW-G0",
    },
    {
      id: "t-15",
      title: "Raat Kali Ek Khwaab Mein Aayi",
      artist: "Kishore Kumar",
      film: "Buddha Mil Gaya",
      year: 0,
      duration: 300,
      videoId: "hunxIf1WrHI",
    },
    {
      id: "t-16",
      title: "Tera Mera Rishta Purana",
      artist: "Mustafa Zahid",
      film: "Awarapan",
      year: 0,
      duration: 300,
      videoId: "g23pmazHwgE",
    },
    {
      id: "t-17",
      title: "Aap Ki Aankhon Mein Kuch",
      artist: "Kishore Kumar & Lata Mangeshkar",
      film: "Ghar",
      year: 0,
      duration: 300,
      videoId: "daxuKHBWiKE",
    },
    {
      id: "t-18",
      title: "Tu Hi Meri Shab Hai",
      artist: "KK",
      film: "Gangster",
      year: 0,
      duration: 300,
      videoId: "cGNcjqXe87U",
    },
    {
      id: "t-19",
      title: "Chookar Mere Man Ko",
      artist: "Kishore Kumar",
      film: "Yaarana",
      year: 0,
      duration: 300,
      videoId: "4w9FBmbCfws",
    },
    {
      id: "t-20",
      title: "Zara Sa",
      artist: "KK",
      film: "Jannat",
      year: 0,
      duration: 300,
      videoId: "-8C_2BBVWk8",
    },
    {
      id: "t-21",
      title: "Zindagi Ke Safar Mein",
      artist: "Kishore Kumar",
      film: "Aap Ki Kasam",
      year: 0,
      duration: 300,
      videoId: "MwCPjspNo2c",
    },
    {
      id: "t-22",
      title: "Alvida",
      artist: "KK",
      film: "Life In A Metro",
      year: 0,
      duration: 300,
      videoId: "hM9QDpLHhdw",
    },
    {
      id: "t-23",
      title: "Yeh Jo Mohabbat Hai",
      artist: "Kishore Kumar",
      film: "Kati Patang",
      year: 0,
      duration: 300,
      videoId: "PB-3_kpHC3w",
    },
    {
      id: "t-24",
      title: "Tera Chehra",
      artist: "Adnan Sami",
      film: "",
      year: 0,
      duration: 300,
      videoId: "zNUs54J3mKo",
    },
    {
      id: "t-25",
      title: "Kya Yahi Pyaar Hai",
      artist: "Kishore Kumar & Lata Mangeshkar",
      film: "Rocky",
      year: 0,
      duration: 300,
      videoId: "3YxZd2SPmpQ",
    },
    {
      id: "t-26",
      title: "Uska Hi Banana",
      artist: "Arijit Singh",
      film: "1920",
      year: 0,
      duration: 300,
      videoId: "3z_5CKVe2MU",
    },
    {
      id: "t-27",
      title: "Log Kehte Hain Main Sharabi Hoon",
      artist: "Kishore Kumar",
      film: "Sharaabi",
      year: 0,
      duration: 300,
      videoId: "3qyXfhbBUbU",
    },
    {
      id: "t-28",
      title: "Tum Jaise Bewadon Ka Sahara Hai",
      artist: "Rajeev Raja",
      film: "",
      year: 0,
      duration: 300,
      videoId: "DFzw1rfzXrI",
    },
    {
      id: "t-29",
      title: "Yeh Kya Hua",
      artist: "Kishore Kumar",
      film: "Amar Prem",
      year: 0,
      duration: 300,
      videoId: "4gkJ-GJasLk",
    },
    {
      id: "t-30",
      title: "Kya Mujhe Pyaar Hai",
      artist: "KK",
      film: "Woh Lamhe",
      year: 0,
      duration: 300,
      videoId: "Gg6NMU4ivXM",
    },
    {
      id: "t-31",
      title: "Kuchh Toh Log Kahenge",
      artist: "Kishore Kumar",
      film: "Amar Prem",
      year: 0,
      duration: 300,
      videoId: "cWNA1rTroHY",
    },
    {
      id: "t-32",
      title: "Tum Hi Ho",
      artist: "Arijit Singh",
      film: "Aashiqui 2",
      year: 0,
      duration: 300,
      videoId: "BjL7AuPsmEk",
    },
    {
      id: "t-33",
      title: "Tu Meri Zindagi Hai",
      artist: "Aashiqui",
      film: "",
      year: 0,
      duration: 300,
      videoId: "a4QyYyloteQ",
    },
    {
      id: "t-34",
      title: "Haan Tu Hain",
      artist: "KK",
      film: "Jannat",
      year: 0,
      duration: 300,
      videoId: "plcI5i3uuTs",
    },
  ],
};

export const playlists: Playlist[] = [playlistOne];